# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

export ZSH="$HOME/.oh-my-zsh"


plugins=( 
    git
    zsh-autosuggestions
    zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh


# Display Pokemon-colorscripts
# Project page: https://gitlab.com/phoneybadger/pokemon-colorscripts#on-other-distros-and-macos
#pokemon-colorscripts --no-title -s -r #without fastfetch
#pokemon-colorscripts --no-title -s -r | fastfetch -c $HOME/.config/fastfetch/config-pokemon.jsonc --logo-type file-raw --logo-height 10 --logo-width 5 --logo -

# fastfetch. Will be disabled if above colorscript was chosen to install
#fastfetch -c $HOME/.config/fastfetch/config-compact.jsonc

# Set-up icons for files/directories in terminal using lsd
alias ls='lsd'
alias l='ls -l'
alias la='ls -a'
alias lla='ls -la'
alias lt='ls --tree'
alias gc="git commit"
alias gs="git status"
alias v="nvim"
alias gp="git push"

export EDITOR="nvim"
export TERMINAL="kitty"

ZSH_THEME=""
autoload -Uz colors && colors

# Username pill + working directory
PROMPT='%K{#1e1e2e}%F{#cdd6f4} %n %f%k %K{#1a1b26}%F{#a9b1d6} %~ %f%k %F{#7aa2f7}›%f '


# Show custom ASCII once per session
#if [[ -z "$ASCII_SHOWN" ]]; then
#  export ASCII_SHOWN=1
#  cat ~/Desktop/'Ascii art.txt'
#fi

